### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by milelo** [gimportexportdevs/gexporter#2]
Samsung S7E / Fenix 5x
Garmin app V5.3
Android app V7
I can't get this to work:
Exported waypoint from locus map app to download directory.
I the gpx is listed in the app.
The gpx is also listed in the 5x app.
When I press start the app reports "download failed".
The 5x can connect to the garmin connect app ok.

**Comment by haraldh** [comment]
Maybe the track is too big, has too many waypoints. Try the option to reduce the waypoints.

Am 23. November 2017 10:01:59 MEZ schrieb Mike Longworth <notifications@github.com>:

**Comment by milelo** [comment]
The gpx only contains a single waypoint.

**Comment by haraldh** [comment]
Sorry, I meant track points, meaning the route consists of hundreds of connected track points.

Am 23. November 2017 19:01:31 MEZ schrieb Mike Longworth <notifications@github.com>:
