### ISSUE TITLE
Bug in Fit file generation (Gpx2Fit.java)

### ISSUE THREAD

**Issue by Whoptimus** [gimportexportdevs/gexporter#3]
The first row of the RecordMesg is missing gspeed info. That's why the the generated fit file contains 2 types of RecordMesg (I don't how to 
better explain it). The if statement at row 604 needs a else statement in the Gpx2Fit.java file.

**Comment by haraldh** [comment]
Well, which speed should be set then? The last timestamp equals the current timestamp, so if the position differs, someone warped in zero time.

**Comment by Whoptimus** [comment]
I think the speed has to be zero. That's the same info like the fit files generated by Garmin Connect.

**Comment by haraldh** [comment]
https://github.com/gimportexportdevs/gexporter/commit/9974a559e30461ec0bdb894103106e3fe1971903
