### ISSUE TITLE
gpx files using <rte> tag are shown as straight lines (osmand files)

### ISSUE THREAD

**Issue by buffoletti** [gimportexportdevs/gexporter#5]
My favourite use of gexporter was the offline way of making gpx with osmand. Since some month osmand has implemented a advanced route builder that saves the gpx files including the points, that were used to create the gpx. The files has the structure of 
```
<gpx version="1.1" creator="OsmAndRouterV2" xmlns="http://www.topografix.com/GPX/1/1" xmlns:osmand="https://osmand.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    ...
  </metadata>
            <rte>
                    <rtept lat="49.5806993" lon="8.1673218">
                            these are the route points
                    </rtept>
                    .....
            </rte>

  <trk>
            <trkseg>
                      <trkpt lat="49.5807026" lon="8.1672835">
                              these are the actually track points
                      </trkpt>
                      .....
            </trkseg>
  </trk>
</gpx>
```

The App will now only transmitt the <rtept> entries, but not the actual <trpt> entries, which have the accurate track information. If I manually remove the <rte> section of the gpx file, it comes through perfectly. 

Is there anyway of making the app skipp the <rte> section?
I am not capable of performing the necessary changes to the scripts, but would very much appreciate if someone could do so. 
The osmand -> gexporter -> Garmin device is the only practicable way of doing offline routing to the watch I know. 
Thanks.

**Comment by haraldh** [comment]
Yes, the code should prefer the `trkseg` if present.

**Comment by haraldh** [comment]
Does version 11 of gexporter work for you?
https://play.google.com/store/apps/details?id=org.surfsite.gexporter

**Comment by buffoletti** [comment]
Hi Harald, V11 does indeed seem to work as expected!
Thank you very much for the quick fix!
