### ISSUE TITLE
No files to serve

### ISSUE THREAD

**Issue by robertbelica** [gimportexportdevs/gexporter#9]
I think that after Android 13 update, I've got "no files to serve from /storage/emulated/0/Download"  and "gimporter CIQ app doesn't seem to be installed. Tap to download.".

There is a gpx file in Download folder and gimporter widget on Garmin works like a charm.

Could you fix it?

![Screenshot_20221030-232215](https://user-images.githubusercontent.com/117046257/198904847-012f2fa3-f226-476d-9bd5-4ac96118f91a.png)

**Comment by fm-sys** [comment]
> gimporter widget on Garmin

Normally, the widget version should be recognized as well.

> I've got "no files to serve from /storage/emulated/0/Download"

On Android 10 this works fine. All files from "Downloads" directory are discovered properly.

However, if you install the latest update you will have the possibility to select a custom directory. Please report back whether this works.

**Comment by robertbelica** [comment]
Hi,Now everything works gr8 (after the update)Nice idea to select custom folder.Thank you very much - very useful app.RegardsRobertOn Oct 31, 2022 21:02, fm-sys ***@***.***> wrote:

gimporter widget on Garmin

Normally, the widget version should be recognized as well.

I've got "no files to serve from /storage/emulated/0/Download"

On Android 10 this works fine. All files from "Downloads" directory are discovered properly.
However, if you install the latest update you will have the possibility to select a custom directory. Please report back whether this works.
